site_name: SuperQ
site_author: Alvin Chen <bollinmore@gmail.com>
nav:
  - Home: index.md
  - About: about.md
  - Leet Code:
    - 1. Two Sum: math/two_sum.md
    - 2. Add Two Numbers: math/add_two_numbers.md
    - 7. Reverse Integer: math/reverse_integer.md
    - 15. 3Sum: two_pointers/3Sum.md
    - 45. Jump Game II: dp/jump_game2.md
    - 55. Jump Game: dp/jump_game.md
    - 62. Unique Paths: dp/unique_paths.md
    - 64. Minimum Path Sum: dp/minimum_path_sum.md
    - 96. Unique Binary Search Trees: dp/unique_binary_search_trees.md
    - 142. Linked List Cycle II: dp/linked_list_cycle2.md
    - 134. Gas Station: array/gas_station.md
    - 292. Nim Game: math/nim_game.md
    - 414. Third Maximum Number: math/third_maximum_number.md
  - Code Snippet:
    - Generate random negative integer: snippet/random_negative_int.md

theme:
    name: bootstrap4
